#!/usr/bin/env bash
set -e

# Path to world66 repo — reads from .env or falls back to sibling directory
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
  WORLD66_DIR=$(grep '^WORLD66_DIR=' "$SCRIPT_DIR/.env" | cut -d= -f2- | tr -d '"'"'" )
fi
WORLD66_DIR="${WORLD66_DIR:-$SCRIPT_DIR/world66}"

if [ ! -d "$WORLD66_DIR/.git" ]; then
  echo "Error: no git repo at $WORLD66_DIR"
  exit 1
fi

cd "$WORLD66_DIR"

echo "==> Pulling latest world66..."
git pull

if [ -z "$(git status --porcelain)" ]; then
  echo "==> No local changes — nothing to submit."
  exit 0
fi

echo "==> Changes found:"
git status --short

BRANCH="tabbi-content-$(date +%Y-%m-%d)"

# If branch already exists, append a counter
if git show-ref --quiet "refs/heads/$BRANCH"; then
  BRANCH="$BRANCH-$(date +%H%M)"
fi

git checkout -b "$BRANCH"
git add .
git commit -m "Content additions from Tabbi"
git push origin "$BRANCH"

gh pr create \
  --title "Content additions from Tabbi ($(date +%Y-%m-%d))" \
  --body "POIs and content written via Tabbi trip planning. Auto-generated by sync-world66.sh."

echo "==> Done. PR created."
